### ISSUE TITLE
"Input string was not in a correct format" exception

### ISSUE THREAD

**Issue by fandrei** [bitpusher/Salient.ReliableHttpClient#6]
Running csharp-bot-development-flow after updating all NuGet packages to latest versions:

```
Input string was not in a correct format.
System.FormatException
   at Salient.ReliableHttpClient.ClientBase.Request[T](RequestMethod method, String target, String uriTemplate, Dictionary`2 headers, Dictionary`2 parameters, ContentType requestContentType, ContentType responseContentType, TimeSpan cacheDuration, Int32 timeout, Int32 retryCount)
   at CIAPI.Rpc.Client.Request[T](RequestMethod method, String target, String uriTemplate, Dictionary`2 parameters, ContentType requestContentType, ContentType responseContentType, TimeSpan cacheDuration, Int32 timeout, Int32 retryCount)
   at CIAPI.Rpc.Client._Market.GetMarketInformation(String MarketId)
   at Monitors.AllServiceMonitor.GetMarketInformation() in d:\projects\City Index\csharp-bot-development-flow\src\Monitors\AllServiceMonitor.cs:line 163
System.FormatException: Input string was not in a correct format.
   at Newtonsoft.Json.Utilities.ConvertUtils.Int32Parse(Char[] chars, Int32 start, Int32 length)
   at Newtonsoft.Json.JsonTextReader.ParseNumber()
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonReader.ReadAsInt32Internal()
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at CIAPI.Serialization.Serializer.DeserializeObject[T](String json)
   at Salient.ReliableHttpClient.ClientBase.Request[T](RequestMethod method, String target, String uriTemplate, Dictionary`2 headers, Dictionary`2 parameters, ContentType requestContentType, ContentType responseContentType, TimeSpan cacheDuration, Int32 timeout, Int32 retryCount)
```

**Comment by bitpusher** [comment]
i think this is related to https://github.com/cityindex/CIAPI.CS/issues/223

**Comment by bitpusher** [comment]
@fandrei it is certainly related to above issue.  i will be pushing a temporary fix today pending online metadata update.

**Comment by bitpusher** [comment]
try updating to CIAPI 10.6.5 and let me know.

**Comment by fandrei** [comment]
@bitpusher, Getting this after updating all packages:

```
    1>d:\projects\City Index\CiapiLatencyCollector\packages\CIAPI.10.6.5\lib\net35\Release\CIAPI.dll : error CS1705: Assembly 'CIAPI, Version=10.6.5.572, Culture=neutral, PublicKeyToken=5dfdbaca97c75bb7' uses 'Salient.ReliableHttpClient, Version=1.4.3.36, Culture=neutral, PublicKeyToken=de2ccdae144c2020' which has a higher version than referenced assembly 'Salient.ReliableHttpClient, Version=1.4.1.34, Culture=neutral, PublicKeyToken=de2ccdae144c2020'
```

**Comment by bitpusher** [comment]
interesting. i have some ideas why this is happening but i would like to pull the project source and make sure.

where is the code?

**Comment by fandrei** [comment]
it seems this issue has disappeared after updating to CIAPI 10.7

btw, when you add text to your message - notification about this won't be sent

**Comment by bitpusher** [comment]
@fandrei 

> btw, when you add text to your message - notification about this won't be sent

are you saying that my comment did not get pushed to you? likely because i didn't '@' you.

**Comment by fandrei** [comment]
@bitpusher, I've got notification with the first line of your message (as a bug reporter), but not with the second. Probably because GitHub doesn't notify about message modifications.
